language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r webservice *
  - mkdir -p deploy
  - mv webservice.zip deploy/webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: webservice-test1-build
    region: us-east-1
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: webservice-test1-build
    key: webservice.zip
    bundle-type: zip
    application: webservice
    deployment_group: webservice-group
    region: us-east-1
    wait-until-deployed: true


# CI 실행 완료 시 메일전송
notifications:
  email:
    recipients:
      - cdgus1514@gmail.com